spring.application.name=lycorisfunServer
server.port=12808
server.servlet.context-path=/lycorisfunServer

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/useforcommon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=dxx5201314

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.lycorisfun.fun.entity